# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c428bd620b47c5bff9d2879e241e6d8d8cb58a5bfafead69f63ad284690c42cd66dcc5545ac012aac7e1923ccd1266195cd7e73f8261bead9eae55432fc3bdf1

test:
  secret_key_base: 43c8c9c69f249cce3ffdf6d20f1c3d556d8300f50501a8a0e05230f3be6e33dc25d6b4f7c4986d895b33ac87f06276710b3d79a707888ec2e29b452709a4d254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
